experiments_folder: d:\repositories\Simulator\experiments\synfire_chain_callback\refract_connectivity_0_025_to_1_and_synaptic_strength_0_025_to_0_1_v3\
variable1: connectivity
variable2: strength
title: connectivity_vs_synapse_strength