common_path: d:\repositories\Simulator\experiments\experiments_imrpovements_final\basic\multiple_times_between_currents_tau_10_conduct\
x_label: t (ms)
y_label: descarcari
binaries:
  - tau_10.00_step_1/output_layer/spikes_N0.bin
  - tau_10.00_step_20/output_layer/spikes_N0.bin
  #- step_5/output_layer/IPSC_N0.bin
  #- step_10/output_layer/spikes_N0.bin
  #- step_20/output_layer/IPSC_N0.bin
labels:
  - Pas 1
  - Pas 20
