layers_folder: d:\repositories\Simulator\experiments\synfire_chain\w_refract_0_5_connectivity_0_025_to_1_and_synaptic_strength_0_025_to_1\connectivity_1.0000_strength_0.0250\
title: 10l_20s_inhi_0_5_tau_80s_exci_0_5_tau
layers:
  - layer01
  - layer02
  - layer03
  - layer04
  - layer05
  - layer06
  - layer07
  - layer08
  - layer09
  - layer10
binaries_prefix: spikes
