layers_folder: d:\repositories\Simulator\experiments\synfire_chain_callback\r_1_connectivity_0.5000_amplitude_0.1000\coonectivity_0.5000_amplitude_0.1000\
layers:
- layer01
- layer01_inhi
- layer02
- layer02_inhi
- layer03
- layer03_inhi
- layer04
- layer04_inhi
- layer05
- layer05_inhi
- layer06
- layer06_inhi
- layer07
- layer07_inhi
- layer08
- layer08_inhi
- layer09
- layer09_inhi
- layer10
title: activity
binaries_prefix: spikes
color_for_inner_substring:
  inhi: blue
default_color: red
