layers_folder: d:\repositories\Simulator\experiments\synfire_chain_callback\r_1_connectivity_0.9250_amplitude_0.0250\coonectivity_0.9250_amplitude_0.0250\
layers:
- layer01
- layer01_inh
- layer02
- layer02_inh
- layer03
- layer03_inh
- layer04
- layer04_inh
- layer05
- layer05_inh
- layer06
- layer06_inh
- layer07
- layer07_inh
- layer08
- layer08_inh
- layer09
- layer09_inh
- layer10
title: activity
binaries_prefix: spikes
