layers_folder: d:\repositories\Simulator\experiments\rerun_probability_plots\debug_80_20_nice\t0\conectivitate_0.2250_amplitudine_0.7000\
layers:
- nivel01
- nivel01_inhi
- nivel02
- nivel02_inhi
- nivel03
- nivel03_inhi
- nivel04
- nivel04_inhi
- nivel05
- nivel05_inhi
- nivel06
- nivel06_inhi
- nivel07
- nivel07_inhi
- nivel08
- nivel08_inhi
- nivel09
- nivel09_inhi
- nivel10
title: "connectivity=0.225 amplitude=0.7"
binaries_prefix: spikes
color_for_inner_substring:
  inhi: blue
default_color: red
