binaries_prefix: spikes
layers:
- layer01
- layer01_inh
- layer02
- layer02_inh
- layer03
- layer03_inh
- layer04
- layer04_inh
- layer05
- layer05_inh
- layer06
- layer06_inh
- layer07
- layer07_inh
- layer08
- layer08_inh
- layer09
- layer09_inh
- layer10
- network.png
layers_folder: d:\repositories\Simulator\experiments\synfire_chain\wide_mapping_space_connectivity_0_03_to_0_60_and_synaptic_strength_0_003_to_0_03\connectivity_0.0300_strength_0.0180
title: connectivity_0.0300_strength_0.0180
