binaries_prefix: spikes
layers:
- layer01
- layer01_inh
- layer02
- layer02_inh
- layer03
- layer03_inh
- layer04
- layer04_inh
- layer05
- layer05_inh
- layer06
- layer06_inh
- layer07
- layer07_inh
- layer08
- layer08_inh
- layer09
- layer09_inh
- layer10
layers_folder: d:\repositories\Simulator\experiments\synfire_chain\mapping_space_connectivity_0_01_to_0_10_and_synaptic_strength\connectivity_0.03_strength_0.10
title: connectivity_0.03_strength_0.10
